services:
  kafka-1:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka-1
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9093 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 45s
    environment:

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'

      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9091,INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-1:9093,EXTERNAL://127.0.0.1:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SSL,INTERNAL:SSL,EXTERNAL:SSL'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'

      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-1.truststore.pkcs12
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-1.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEY_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''

      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - ./security/kafka-1-creds:/etc/kafka/secrets
      - kafka1_data:/var/lib/kafka/data
    networks:
      - flight-net

  kafka-2:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka-2
    ports:
      - "9094:9094"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9095 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 45s
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9091,INTERNAL://0.0.0.0:9095,EXTERNAL://0.0.0.0:9094'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-2:9095,EXTERNAL://127.0.0.1:9094'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SSL,INTERNAL:SSL,EXTERNAL:SSL'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-2.truststore.pkcs12
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-2.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEY_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - ./security/kafka-2-creds:/etc/kafka/secrets
      - kafka2_data:/var/lib/kafka/data
    networks:
      - flight-net

  kafka-3:
    image: confluentinc/cp-kafka:7.7.0
    hostname: kafka-3
    ports:
      - "9096:9096"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9097 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 45s
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-1:9091,2@kafka-2:9091,3@kafka-3:9091'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_LISTENERS: 'CONTROLLER://0.0.0.0:9091,INTERNAL://0.0.0.0:9097,EXTERNAL://0.0.0.0:9096'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://kafka-3:9097,EXTERNAL://127.0.0.1:9096'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:SSL,INTERNAL:SSL,EXTERNAL:SSL'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
      KAFKA_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-3.truststore.pkcs12
      KAFKA_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_TRUSTSTORE_TYPE: PKCS12
      KAFKA_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/kafka.kafka-3.keystore.pkcs12
      KAFKA_SSL_KEYSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_KEYSTORE_TYPE: PKCS12
      KAFKA_SSL_KEY_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_SSL_CLIENT_AUTH: 'required'
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_NUM_PARTITIONS: 6
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    volumes:
      - ./security/kafka-3-creds:/etc/kafka/secrets
      - kafka3_data:/var/lib/kafka/data
    networks:
      - flight-net

  api-producer:
    build: ./services/api-producer
    container_name: flight-api-producer
    ports:
    - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; urllib.request.urlopen('http://localhost:8000/healthcheck')\" || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    depends_on:
      kafka-1: { condition: service_healthy }
      kafka-2: { condition: service_healthy }
      kafka-3: { condition: service_healthy }
    environment:
      KAFKA_BOOTSTRAP: kafka-1:9093,kafka-2:9095,kafka-3:9097
      TOPIC_EVENTS: flight.telemetry
      KAFKA_SECURITY_PROTOCOL: SSL
      KAFKA_SSL_CA_LOCATION: /app/security/ca.crt
      KAFKA_SSL_CERTIFICATE_LOCATION: /app/security/client-creds/kafka.client.certificate.pem
      KAFKA_SSL_KEY_LOCATION: /app/security/client-creds/kafka.client.key
    volumes:
      - ./security:/app/security:ro
    networks:
      - flight-net

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      kafka-1: { condition: service_healthy }
      kafka-2: { condition: service_healthy }
      kafka-3: { condition: service_healthy }
    environment:
      KAFKA_CLUSTERS_0_NAME: flight-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9093,kafka-2:9095,kafka-3:9097
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SSL
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION: /app/security/kafka-1-creds/kafka.kafka-1.truststore.pkcs12
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION: /app/security/kafka-1-creds/kafka.kafka-1.keystore.pkcs12
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD: ${KAFKA_SSL_PASSWORD}
      KAFKA_CLUSTERS_0_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ''
    volumes:
      - ./security:/app/security:ro
    networks:
      - flight-net

networks:
  flight-net:
    driver: bridge

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data: