AIRLINES: dict[str, str] = {
    "KL": "KLM",
    "AF": "Air France",
    "DL": "Delta",
    "AZ": "ITA Airways",
    "KE": "Korean Air",
    "MU": "China Eastern",
    "CZ": "China Southern",
    "VS": "Virgin Atlantic",
    "XQ": "SunExpress",

    "LH": "Lufthansa",
    "LX": "SWISS",
    "OS": "Austrian Airlines",
    "SN": "Brussels Airlines",
    "TK": "Turkish Airlines",
    "SK": "SAS Scandinavian",
    "AC": "Air Canada",
    "UA": "United Airlines",
    "NH": "ANA All Nippon Airways",
    "SQ": "Singapore Airlines",
    "TG": "Thai Airways",
    "EW": "Eurowings",
    "EI": "Air Lingus",

    "BA": "British Airways",
    "IB": "Iberia",
    "AY": "Finnair",
    "AA": "American Airlines",
    "QR": "Qatar Airways",
    "CX": "Cathay Pacific",
    "JL": "Japan Airlines",
    "RJ": "Royal Jordanian",
    "MH": "Malaysia Airlines",

    "HV": "Transavia",
    "OR": "TUI Fly",
    "VY": "Vueling",
    "FR": "Ryanair",
    "U2": "easyJet",
    "EC": "easyJet",
    "EZY": "easyJet",
    "PC": "Pegasus Airlines",
    "W6": "Wizz Air",
    "DY": "Norwegian Air Shuttle",
    "D8": "Norwegian Air Int.",
    "BT": "airBaltic",
    "JU": "Air Serbia",
    "TP": "TAP Air Portugal",
    "LO": "LOT Polish Airlines",
    "OK": "Czech Airlines",
    "AB": "Air Berlin",
    "X3": "TUIfly",
    "DE": "Condor",
    "BY": "TUI Airways",
    "NK": "Spirit Airlines",
    "B6": "JetBlue",
    "WN": "Southwest Airlines",
    "F9": "Frontier Airlines",
    "AS": "Alaska Airlines",
    "OU": "Croatia Airlines",
    "RO": "TAROM",

    "EK": "Emirates",
    "EY": "Etihad Airways",
    "SV": "Saudia",
    "MS": "EgyptAir",
    "ET": "Ethiopian Airlines",
    "KQ": "Kenya Airways",
    "WY": "Oman Air",
    "GF": "Gulf Air",
    "FZ": "flydubai",
    "UL": "SriLankan Airlines",
    "AI": "Air India",
    "6E": "IndiGo",
    "VN": "Vietnam Airlines",
    "PR": "Philippine Airlines",
    "BR": "EVA Air",
    "CI": "China Airlines",
    "OZ": "Asiana Airlines",
    "GA": "Garuda Indonesia",
}

def airline_name(iata_code: str | None) -> str | None:
    """Return the full airline name, or None if unknown."""
    if not iata_code:
        return None
    return AIRLINES.get(iata_code.upper())